services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=paymentdb'
      - 'MONGO_INITDB_ROOT_PASSWORD=mandragora'
      - 'MONGO_INITDB_ROOT_USERNAME=mandragora'
    ports:
      - '27017:27017'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=paymentdb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'