{
 "title": "SOLID - Logs Centralizados (Loki)",
 "tags": [
  "solid",
  "logs",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs - Payment API",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"payment-api\"}"
    }
   ]
  },
  {
   "title": "Logs - Receipt API",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{service=\"receipt-api\"}"
    }
   ]
  },
  {
   "title": "Logs - PostgreSQL",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service=\"postgres-payments\"} "
    },
    {
     "expr": "{service=\"postgres-receipts\"}"
    }
   ]
  },
  {
   "title": "Logs - RabbitMQ",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{service=\"rabbitmq\"}"
    }
   ]
  },
  {
   "title": "Logs - Nginx",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{service=\"nginx-lb\"}"
    }
   ]
  },
  {
   "title": "Logs - Infraestrutura (Prometheus/Loki/Tempo)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{service=~\"prometheus|loki|tempo|alertmanager|promtail\"}"
    }
   ]
  },
  {
   "title": "ERROR/WARN por Servico (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(count_over_time({service=~\"payment-api|receipt-api\"} |~ \"(?i)error|exception\" [1m])) by (service)",
     "legendFormat": "{{service}} errors"
    },
    {
     "expr": "sum(count_over_time({service=~\"payment-api|receipt-api\"} |~ \"(?i)warn\" [1m])) by (service)",
     "legendFormat": "{{service}} warns"
    }
   ]
  }
 ]
}