CREATE TABLE PAYMENTS (
    ID UUID PRIMARY KEY,
    AMOUNT NUMERIC(19,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    EMAIL VARCHAR(255),
    PAYMENT_METHOD VARCHAR(50) NOT NULL
);

CREATE INDEX idx_payments_status ON payments(STATUS);
CREATE INDEX idx_payments_email ON payments(EMAIL);