# Usa uma imagem completa com Maven e JDK
FROM maven:3.9-eclipse-temurin-21

# Define o diretório de trabalho
WORKDIR /app

# Copia todo o código-fonte e o pom.xml
COPY . .

RUN mvn clean package -DskipTests && \
    cp target/*.jar app.jar

EXPOSE 8083

ENTRYPOINT ["java", "-jar", "app.jar"]