events { worker_connections 1024; }

http {
    # Define o grupo de servidores para a API de pagamentos.
    upstream payment_api_upstream {
        server payment-api:8082;
    }

    # Define o grupo de servidores para a API de recibos.
    upstream receipt_api_upstream {
        server receipt-api:8083;
    }

    server {
        listen 80;

        # Rota para a API de pagamentos
        # Todas as requisições que começam com /api/payments são encaminhadas.
        location /api/payments {
            # Ao não especificar um caminho no proxy_pass,
            # o Nginx anexa o URI original do pedido (ex: /api/payments/host).
            proxy_pass http://payment_api_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Rota para a API de recibos
        location /api/receipts {
            proxy_pass http://receipt_api_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}