name: CI/CD com Docker e Docker Hub

on:
  push:
    branches:
      - feat/docker

jobs:
  build-and-push:
    name: Build e Push para o Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Logar no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e fazer push da imagem payment-api
        uses: docker/build-push-action@v5
        with:
          context: ./PaymentSolidApi
          file: ./PaymentSolidApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/payment-api:latest

      - name: Construir e fazer push da imagem receipt-api
        uses: docker/build-push-action@v5
        with:
          context: ./ReceiptApi
          file: ./ReceiptApi/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/receipt-api:latest

  deploy:
    name: Deploy Simulado em Cloud
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Simular Deploy para Cloud
        run: |
          echo "Iniciando deploy simulado para a Cloud..."
          echo "Imagens a serem deployadas:"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/payment-api:latest"
          echo "- ${{ secrets.DOCKERHUB_USERNAME }}/receipt-api:latest"
          echo "Aguardando 5 segundos para simular a comunicação com os serviços..."
          sleep 5
          echo "Deploy simulado concluído com sucesso."